name: Android CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  android:
    runs-on: android-kmp

    steps:
      - uses: actions/checkout@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and test
        run: |
          ./gradlew \
            check \
            assembleDebug \
            --no-daemon \
            --max-workers=2 \
            -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g"
