package com.meloda.fast.api

enum class VKApiKeys {
    READ_MESSAGE,
    RESTORE_MESSAGE,
    UPDATE_MESSAGE,
    NEW_MESSAGE,
    EDIT_MESSAGE,
    DELETE_MESSAGE,
    UPDATE_CONVERSATION,

    UPDATE_USER,

    UPDATE_GROUP
}