name: Android CI

on:
  push:
    branches: [ "main" ]

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build_apk_aab:
    runs-on: ubuntu-latest
    name: Build full artifacts
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and sign debug APKs
        run: ./gradlew assembleDebug

      - name: Build and sign release APKs
        run: ./gradlew assembleRelease

      - name: Upload full-debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-full-debug.apk
          path: app/build/outputs/apk/full/debug/app-full-debug.apk

      - name: Upload full-release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-full-release.apk
          path: app/build/outputs/apk/full/release/app-full-release.apk
